In [1]:
import pandas as pd
import numpy as np


coef_path = r"C:\Users\HP\OneDrive\Escritorio\David Guzzi\Github\Python-Projects\astrea\logit_coefficients.csv"
coef = pd.read_csv(coef_path, delimiter=",")
coef.head()

Variable  Coefficient
0           const    -3.289498
1           price    -0.584335
2  brand_strength     0.310713
3   quality_score     1.200612

In [2]:
data_path = r"C:\Users\HP\OneDrive\Escritorio\David Guzzi\Github\Python-Projects\astrea\synthetic_choice_data.csv"
data = pd.read_csv(data_path, delimiter=",")
data.head()

respondent_id  trip_id  product_id     price  brand_strength  \
0              0        0          13  2.911052        0.948886   
1              0        0           5  2.403951        0.785176   
2              0        0           7  8.795585        0.514234   
3              0        0          10  1.185260        0.607545   
4              0        0          12  8.491984        0.065052   

   quality_score  group  choice  
0       4.579309      0       0  
1       3.650089      0       0  
2       3.080272      0       0  
3       4.878339      0       1  
4       4.757996      0       0

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 75000 entries, 0 to 74999
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   respondent_id   75000 non-null  int64  
 1   trip_id         75000 non-null  int64  
 2   product_id      75000 non-null  int64  
 3   price           75000 non-null  float64
 4   brand_strength  75000 non-null  float64
 5   quality_score   75000 non-null  float64
 6   group           75000 non-null  int64  
 7   choice          75000 non-null  int64  
dtypes: float64(3), int64(5)
memory usage: 4.6 MB


In [4]:
data["choice"].unique()


array([0, 1], dtype=int64)

In [5]:
data["group"].unique()

array([0, 1], dtype=int64)

In [15]:
data["group"].value_counts()

group
1    38100
0    36900
Name: count, dtype: int64

In [14]:
data.groupby(['group', 'respondent_id']).size()

group  respondent_id
0      0                50
       1                50
       3                50
       4                50
       6                50
                        ..
1      1492             50
       1493             50
       1496             50
       1498             50
       1499             50
Length: 1500, dtype: int64

In [7]:
data["respondent_id"].value_counts()

respondent_id
0       50
997     50
1006    50
1005    50
1004    50
        ..
497     50
496     50
495     50
494     50
1499    50
Name: count, Length: 1500, dtype: int64

In [8]:
data["trip_id"].unique()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64)

In [9]:
data["product_id"].unique()

array([13,  5,  7, 10, 12,  0,  3,  1, 19, 15, 18,  9, 17, 14, 16,  8,  2,
       11,  6,  4], dtype=int64)

In [19]:
data[data["group"] == 0]['respondent_id'].nunique()

738

In [20]:
data[data["group"] == 1]['respondent_id'].nunique()

762

In [21]:
data[data["respondent_id"] == 0].sort_values(by='product_id')

respondent_id  trip_id  product_id     price  brand_strength  \
29              0        5           0  4.370861        0.611853   
5               0        1           0  4.370861        0.611853   
41              0        8           0  4.370861        0.611853   
13              0        2           0  4.370861        0.611853   
48              0        9           1  9.556429        0.139494   
10              0        2           1  9.556429        0.139494   
27              0        5           1  9.556429        0.139494   
30              0        6           2  7.587945        0.292145   
6               0        1           3  6.387926        0.366362   
1               0        0           5  2.403951        0.785176   
7               0        1           5  2.403951        0.785176   
47              0        9           6  1.522753        0.199674   
49              0        9           7  8.795585        0.514234   
9               0        1           7  8.795585        0.514234   
2               0        0           7  8.795585        0.514234   
40              0        8           7  8.795585        0.514234   
35              0        7           8  6.410035        0.592415   
21              0        4           8  6.410035        0.592415   
26              0        5           8  6.410035        0.592415   
33              0        6           8  6.410035        0.592415   
20              0        4           9  7.372653        0.046450   
34              0        6           9  7.372653        0.046450   
45              0        9           9  7.372653        0.046450   
28              0        5           9  7.372653        0.046450   
37              0        7           9  7.372653        0.046450   
16              0        3           9  7.372653        0.046450   
25              0        5          10  1.185260        0.607545   
3               0        0          10  1.185260        0.607545   
31              0        6          10  1.185260        0.607545   
42              0        8          11  9.729189        0.170524   
46              0        9          11  9.729189        0.170524   
36              0        7          12  8.491984        0.065052   
12              0        2          12  8.491984        0.065052   
4               0        0          12  8.491984        0.065052   
0               0        0          13  2.911052        0.948886   
22              0        4          13  2.911052        0.948886   
8               0        1          13  2.911052        0.948886   
32              0        6          13  2.911052        0.948886   
23              0        4          14  2.636425        0.965632   
38              0        7          14  2.636425        0.965632   
18              0        3          14  2.636425        0.965632   
43              0        8          14  2.636425        0.965632   
14              0        2          15  2.650641        0.808397   
24              0        4          15  2.650641        0.808397   
19              0        3          16  3.738180        0.304614   
17              0        3          17  5.722808        0.097672   
15              0        3          18  4.887505        0.684233   
44              0        8          18  4.887505        0.684233   
39              0        7          19  3.621062        0.440152   
11              0        2          19  3.621062        0.440152   

    quality_score  group  choice  
29       1.488153      0       0  
5        1.488153      0       0  
41       1.488153      0       0  
13       1.488153      0       0  
48       2.980708      0       0  
10       2.980708      0       0  
27       2.980708      0       0  
30       1.137554      0       0  
6        4.637282      0       0  
1        3.650089      0       0  
7        3.650089      0       0  
47       2.246844      0       1  
49       3.080272      0       0  
9        3.080272      0       0  
2        3

In [25]:
data.groupby(['respondent_id']).agg({'choice': 'sum'}).reset_index().sort_values(by='choice', ascending=True)

respondent_id  choice
0                 0      10
1005           1005      10
1004           1004      10
1003           1003      10
1002           1002      10
...             ...     ...
495             495      10
494             494      10
493             493      10
502             502      10
1499           1499      10

[1500 rows x 2 columns]